[build-system]
requires = ["maturin>=1.14.1"]
build-backend = "maturin"

[tool.maturin]
# Build artifacts with the specified Cargo profile
profile = "release"
module-name = "thrl"

[project]
name = "thrl-rs"
version = "0.2.2"
description = "Touhou Reinforcement Learning Framework"
requires-python = ">=3.13"
dependencies = [
  "numpy>=2.5.3",
  "torch==2.14.0+xpu",
]

[tool.uv]
index-strategy = "unsafe-best-match"
#reinstall-package = ["thrl"] # So I do not need to advance number every time.

[tool.uv.sources]
torch = { index = "pytorch-xpu" }

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
