[build-system]
requires = ["maturin>=1.14.1"]
build-backend = "maturin"
[tool.maturin]
# Build artifacts with the specified Cargo profile
profile = "release"
[project]
name = "rrr"
version = "0.1.12"
description = "Touhou Reinforcement Learning Framework"
requires-python = ">=3.14"
dependencies = [
  "matplotlib>=3.11.1",
  "numpy>=2.5.1",
  "packaging>=26.2",
  "pandas>=3.0.5",
  "safetensors>=0.7.0",
  "torch==2.13.0+xpu",
  "tqdm>=4.70.0",
]

[tool.uv]
index-strategy = "unsafe-best-match"
#reinstall-package = ["rrr"] # So I do not need to advance number every time.

[tool.uv.sources]
torch = { index = "pytorch-xpu" }
torchvision = { index = "pytorch-xpu" }
torchaudio = { index = "pytorch-xpu" }

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
