[package]
name = "thmp"
version = "0.2.2"
edition = "2024"
license = "GPL-3.0-or-later"
description = "Map viewer for thrl project"
repository = "https://codeberg.org/thrl/thrl"

[dependencies]
thrl = { version = "0.2.2", path = "..", default-features = false }
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "glow", "x11", "wayland"] }
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"