# This configuration is for actual training pipeline.
[dosbox]
machine=pc98
memsize=8

[cpu]
core=normal
cputype=486
cycles=23880

[pc98]
pc-98 enable grcg=true
pc-98 enable egc=true
pc-98 enable 16-color=true
pc-98 start gdc at 5mhz=false
pc-98 fm board=board86
pc-98 time stamp=true
pc-98 buffer page flip=false
pc-98 video mode=24khz

[render]
frameskip=0
aspect=false
scaler=none

[vsync]
vsyncmode=off

[sdl]
output=surface
videodriver=dummy
fullscreen=false
showmenu=false
priority=higher,higher

[mixer]
nosound=true
